#%RAML 1.0 NamedExample
records_in_the_table:
-
  -ID: "O-010"
  -BuyerPatyName : "om"
  -OrderStatus : "Received"
  -OrderStartDate: 12-02-2021
  -OrderEndDate: 12334334
  -GrossAmounnt: 32452.32
-
  -ID: "O-014"
  -BuyerPatyName : "Rohit"
  -OrderStatus : "Received"
  -OrderStartDate: 14-12-2020
  -Date: 22122344
  -GrossAmounnt: 84364.34